version: "3.8"
services:
  node-alkemy-app:
    build:
      context: .
      args: 
        NODE_ENV: test
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm run test
    env_file:
      - ./.env.test
