USE nico_alkemi

CREATE TABLE Users (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
email VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
username VARCHAR(30) NOT NULL,
enable BOOLEAN NOT NULL DEFAULT false
)

CREATE TABLE Movies (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
image VARCHAR(50) NOT NULL,
description VARCHAR(50) NOT NULL,
rating INT(6) NOT NULL,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
contentTypeId INT(6) NOT NULL,
genderTypeId INT(6) NOT NULL,
)